name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main  # deploy every time you push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # <-- change to match your local version

      - name: Install dependencies
        run: npm ci

      - name: Build and Export
        run: |
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          cname: daviderwin.me
          enable_jekyll: false
